### ISSUE TITLE
Illustrations pour le tutoriel Programmer un chifoumi

### ISSUE THREAD

**Issue by aureliendossantos** [gamedevalliance/wiki#35]
Actuellement les images ont été récupérées du site Biloucorp. Ce serait bien d'avoir des illustrations correspondant mieux au style graphique du wiki.
https://wiki.rpgmakeralliance.com/programmerunchifoumi

**Comment by Jauke** [comment]
Avec XMind je faisais de jolies choses côté arborescence / organisation. Il faudrait que je check s’il n’y a pas un équivalent open-source, sinon c’est un bon freeware
