### ISSUE TITLE
Liste des moteurs de jeu

### ISSUE THREAD

**Issue by aureliendossantos** [gamedevalliance/wiki#64]
Une page listant des moteurs de jeu pertinents, afin de conseiller aux lecteurs un moteur adapté à leur projet. Plus tard, ce résumé servira également pour l'accueil du portail de chaque moteur.

- [ ] Unity
- [ ] Unreal Engine
- [x] Godot
- [x] GameMaker
- [ ] Construct
- [x] RPG Maker
- [x] Ren'Py
- [x] Twine
- [ ] PICO-8
- [x] Bitsy

**Comment by Princesseuh** [comment]
Peut-être que cette issue devrait être reformulée considérant les changements récents de la vision de RMA?  Une page qui liste les moteurs ne me semble plus vraiment intéressante

**Comment by GoulvenC** [comment]
Ne correspond plus à la vision de GDA.
